// Payment controller for Cardano DApp
const Payment = require('../models/Payment');

// Create a new payment
async function createPayment(req, res) {
  try {
    const { invoiceId, senderAddress, receiverAddress, amount, transactionHash } = req.body;
    
    // Validate input
    if (!invoiceId || !senderAddress || !receiverAddress || !amount || !transactionHash) {
      return res.status(400).json({ error: 'Missing required fields' });
    }
    
    // Create new payment
    const newPayment = new Payment(
      null, // ID will be generated by DB
      invoiceId,
      senderAddress,
      receiverAddress,
      amount,
      transactionHash,
      'pending', // Initial status
      new Date()
    );
    
    const savedPayment = await Payment.save(newPayment);
    res.status(201).json(savedPayment);
  } catch (error) {
    console.error('Error creating payment:', error);
    res.status(500).json({ error: 'Internal server error' });
  }
}

// Get payment by ID
async function getPaymentById(req, res) {
  try {
    const { id } = req.params;
    const payment = await Payment.findById(id);
    
    if (!payment) {
      return res.status(404).json({ error: 'Payment not found' });
    }
    
    res.json(payment);
  } catch (error) {
    console.error('Error fetching payment:', error);
    res.status(500).json({ error: 'Internal server error' });
  }
}

// Get payments by invoice ID
async function getPaymentsByInvoiceId(req, res) {
  try {
    const { invoiceId } = req.params;
    const payments = await Payment.findByInvoiceId(invoiceId);
    res.json(payments);
  } catch (error) {
    console.error('Error fetching payments:', error);
    res.status(500).json({ error: 'Internal server error' });
  }
}

// Update payment status
async function updatePaymentStatus(req, res) {
  try {
    const { id } = req.params;
    const { status } = req.body;
    
    // Validate status
    if (!['pending', 'confirmed', 'failed'].includes(status)) {
      return res.status(400).json({ error: 'Invalid status' });
    }
    
    const updated = await Payment.updateStatus(id, status);
    
    if (!updated) {
      return res.status(404).json({ error: 'Payment not found' });
    }
    
    res.json({ message: 'Payment status updated successfully' });
  } catch (error) {
    console.error('Error updating payment status:', error);
    res.status(500).json({ error: 'Internal server error' });
  }
}

module.exports = {
  createPayment,
  getPaymentById,
  getPaymentsByInvoiceId,
  updatePaymentStatus
};