// Stablecoin controller for Cardano DApp
const StablecoinTx = require('../models/StablecoinTx');

// Create a new stablecoin transaction
async function createTransaction(req, res) {
  try {
    const { userId, tokenName, amount, senderAddress, receiverAddress, transactionHash } = req.body;
    
    // Validate input
    if (!userId || !tokenName || !amount || !senderAddress || !receiverAddress || !transactionHash) {
      return res.status(400).json({ error: 'Missing required fields' });
    }
    
    // Create new transaction
    const newTransaction = new StablecoinTx(
      null, // ID will be generated by DB
      userId,
      tokenName,
      amount,
      senderAddress,
      receiverAddress,
      transactionHash,
      'pending', // Initial status
      new Date()
    );
    
    const savedTransaction = await StablecoinTx.save(newTransaction);
    res.status(201).json(savedTransaction);
  } catch (error) {
    console.error('Error creating stablecoin transaction:', error);
    res.status(500).json({ error: 'Internal server error' });
  }
}

// Get transaction by ID
async function getTransactionById(req, res) {
  try {
    const { id } = req.params;
    const transaction = await StablecoinTx.findById(id);
    
    if (!transaction) {
      return res.status(404).json({ error: 'Transaction not found' });
    }
    
    res.json(transaction);
  } catch (error) {
    console.error('Error fetching transaction:', error);
    res.status(500).json({ error: 'Internal server error' });
  }
}

// Get transactions by user ID
async function getTransactionsByUser(req, res) {
  try {
    const { userId } = req.params;
    const { limit } = req.query;
    const transactions = await StablecoinTx.findByUserId(userId, parseInt(limit) || 50);
    res.json(transactions);
  } catch (error) {
    console.error('Error fetching transactions:', error);
    res.status(500).json({ error: 'Internal server error' });
  }
}

// Get transactions by token name
async function getTransactionsByToken(req, res) {
  try {
    const { tokenName } = req.params;
    const { limit } = req.query;
    const transactions = await StablecoinTx.findByTokenName(tokenName, parseInt(limit) || 50);
    res.json(transactions);
  } catch (error) {
    console.error('Error fetching transactions:', error);
    res.status(500).json({ error: 'Internal server error' });
  }
}

// Update transaction status
async function updateTransactionStatus(req, res) {
  try {
    const { id } = req.params;
    const { status } = req.body;
    
    // Validate status
    if (!['pending', 'confirmed', 'failed'].includes(status)) {
      return res.status(400).json({ error: 'Invalid status' });
    }
    
    const updated = await StablecoinTx.updateStatus(id, status);
    
    if (!updated) {
      return res.status(404).json({ error: 'Transaction not found' });
    }
    
    res.json({ message: 'Transaction status updated successfully' });
  } catch (error) {
    console.error('Error updating transaction status:', error);
    res.status(500).json({ error: 'Internal server error' });
  }
}

module.exports = {
  createTransaction,
  getTransactionById,
  getTransactionsByUser,
  getTransactionsByToken,
  updateTransactionStatus
};