// User controller for Cardano DApp
const User = require('../models/User');

// Create a new user
async function createUser(req, res) {
  try {
    const { walletAddress, email } = req.body;
    
    // Validate input
    if (!walletAddress) {
      return res.status(400).json({ error: 'Wallet address is required' });
    }
    
    // Check if user already exists
    const existingUser = await User.findByWalletAddress(walletAddress);
    if (existingUser) {
      return res.status(409).json({ error: 'User with this wallet address already exists' });
    }
    
    // Create new user
    const newUser = new User(
      null, // ID will be generated by DB
      walletAddress,
      email,
      new Date()
    );
    
    const savedUser = await User.save(newUser);
    res.status(201).json(savedUser);
  } catch (error) {
    console.error('Error creating user:', error);
    res.status(500).json({ error: 'Internal server error' });
  }
}

// Get user by wallet address
async function getUserByWallet(req, res) {
  try {
    const { walletAddress } = req.params;
    const user = await User.findByWalletAddress(walletAddress);
    
    if (!user) {
      return res.status(404).json({ error: 'User not found' });
    }
    
    res.json(user);
  } catch (error) {
    console.error('Error fetching user:', error);
    res.status(500).json({ error: 'Internal server error' });
  }
}

// Get user by ID
async function getUserById(req, res) {
  try {
    const { id } = req.params;
    const user = await User.findById(id);
    
    if (!user) {
      return res.status(404).json({ error: 'User not found' });
    }
    
    res.json(user);
  } catch (error) {
    console.error('Error fetching user:', error);
    res.status(500).json({ error: 'Internal server error' });
  }
}

module.exports = {
  createUser,
  getUserByWallet,
  getUserById
};